name: default

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: "adopt"

      - name: Create local.properties file
        run: echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > local.properties

      - name: Analyze code with ktlint
        run: ./gradlew ktlintCheck

      - name: Analyze code with detekt
        run: ./gradlew detekt

      - name: Build project
        run: ./gradlew build

      - name: Test it all
        run: ./gradlew test
